# Important Notes:
# Every field you add must be added to the root build.gradle1 expandProps map.

# Project
mod_version=3.0.0
maven_group=cn.evole.mods

yaml_version=4.1.2
onebot_client_version=0.4.3
mixin_extras_version=0.3.5
lombok_version = 1.18.44
jupiter_neoforge_version=5891108
jupiter_fabric_version=5891107
modmenu_version=11.0.3
java_version = 21
enabled_platforms=fabric,neoforge
# Common
mod_id=mcbot
mod_name=McBot
mod_author=cnlimiter
mod_maintainer=Minecraft0122
license=GPL-3.0-or-later
credits=原作：cnlimiter 与 Nova Committee；现维护者：Minecraft0122
description=连接 Minecraft 服务器与 QQ 群，支持双向聊天转发和服务器信息查询命令。
minecraft_version_range=[1.21.1,1.21.2)
minecraft_version=1.21.1

# Mappings
mappings_channel = parchment
mappings_version = 2023.09.03

# Fabric
fabric_loader_version = 0.16.10
fabric_api_version = 0.115.0

# Forge
forge_version=47.3.12
forge_loader_version_range=[46,)
forge_version_range=[46,)

# NeoForge
neoforge_version=21.1.84
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
