# 重要说明：新增的资源替换字段也必须加入根目录 build.gradle 的 replaceProperties 映射。

# 项目
mod_version=2.3.1
maven_group=cn.evole.mods

onebot_client_version=0.4.3
lombok_version = 1.18.44
jupiter_forge_version=5881564
jupiter_fabric_version=5881562
modmenu_version=7.2.2
enabled_platforms=fabric,forge
# 通用信息
mod_id=mcbot
mod_name=McBot
mod_author=cnlimiter
license=GPL-3.0-or-later
credits=
description=连接 Minecraft 服务器与 QQ 群，支持双向聊天转发和服务器信息查询命令。
minecraft_version=1.20.1
mod_version_label=release

# Fabric 平台
fabric_loader_version = 0.16.9
fabric_loader_version_range = >=0.16.9
fabric_api_version = 0.92.2
fabric_api_version_range = >=0.92.2
fabric_minecraft_version_range = 1.20.1

# Forge 平台
forge_version=47.3.12
forge_loader_version_range=[47,48)
forge_version_range=[47.3.12,48)
forge_minecraft_version_range=[1.20.1]

# Gradle 设置
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
