apply(plugin: "dev.architectury.loom")
apply(plugin: "maven-publish")
apply(plugin: "com.replaymod.preprocess")
apply(plugin: "com.github.johnrengelman.shadow")

int mcVersion = 1

preprocess {
    mcVersion = vars.get().get("MC")
}


repositories {
    mavenCentral()
    maven { url 'https://maven.mohistmc.com/' }
    maven { url 'https://jitpack.io' }
    ivy {
        name = 'OneBotGitHubReleases'
        url = 'https://github.com/cnlimiter/onebot-client/releases/download'
        patternLayout {
            artifact 'v[revision]/[artifact]-[revision].[ext]'
        }
        metadataSources { artifact() }
        content { includeModule 'cn.evole.onebot', 'OneBot-Client' }
    }

}

configurations {
    shadowBundle
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    forge "net.minecraftforge:forge:${project.minecraft_version}-${project.forge_version}"


    implementation shadowBundle("cn.evole.onebot:OneBot-Client:${onebot_client_version}") {transitive = false}
    implementation files("${rootDir}/libs/AtomConfig-Toml-0.1.5.jar")
    shadowBundle files("${rootDir}/libs/AtomConfig-Toml-0.1.5.jar")

    if (mcVersion == 11605) include ("org.slf4j:slf4j-api:2.0.7")
    compileOnly ("org.projectlombok:lombok:1.18.36")
    annotationProcessor ("org.projectlombok:lombok:1.18.36")

}

loom {
    silentMojangMappingsLicense()
}

remapJar {
    remapperIsolation = true
    inputFile.set(shadowJar.archiveFile)
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = "dev-shadow"
}


tasks.register('copyJars', Copy) {
    delete "$projectDir/build/libs"
    delete "$rootDir/build/libs"
    from "$projectDir/build/libs"
    into "$rootDir/build/libs"
}

buildNeeded.finalizedBy("copyJars")


sourceCompatibility = JavaVersion.VERSION_1_8
targetCompatibility = JavaVersion.VERSION_1_8

version = project.mod_version + "-forge"
group = project.maven_group
archivesBaseName = project.archives_base_name + "-" + project.minecraft_dependency

processResources {
    outputs.upToDateWhen { false }

    filesMatching("META-INF/mods.toml") {
        expand([
                "minecraft_version_range"   : project.minecraft_version_range,
                "mod_id"              : project.mod_id,
                "mod_name"            : project.archives_base_name,
                "mod_version"         : project.version
        ])

    }
}

tasks.withType(JavaCompile).configureEach {
    options.setEncoding("UTF-8")
}

jar {
    from("../../../LICENSE") {
        rename { "${it}_${project.archives_base_name}" }
    }
}


publishing {
    publications {
        create("mavenJava", MavenPublication) {
            from(components.java)
            version("${project.version}")
            artifactId("${project.archives_base_name}-${project.minecraft_dependency}")
            groupId("${project.maven_group}")
        }
    }

    repositories {
        mavenLocal()
        if (System.getenv('MAVEN_USERNAME') != null && System.getenv('MAVEN_PASSWORD') != null) {
            maven {
                name 'release'
                url = 'https://maven.nova-committee.cn/releases'

                credentials {
                    username System.getenv('MAVEN_USERNAME')
                    password System.getenv('MAVEN_PASSWORD')
                }
            }
        }
    }
}
