println "Using Minecraft: $minecraft_version"

architectury {
    common rootProject.enabled_platforms.split(',')
}

dependencies {
    modImplementation ("net.fabricmc:fabric-loader:$rootProject.fabric_loader_version")

    implementation ("cn.evole.onebot:OneBot-Client:$onebot_client_version"){transitive = false}
    implementation ("com.github.houbb:csv:0.2.0")
    modImplementation ("curse.maven:jupiter-1072905:$jupiter_fabric_version")
    compileOnly ("org.projectlombok:lombok:$lombok_version")
    annotationProcessor ("org.projectlombok:lombok:$lombok_version")
    testImplementation ("org.junit.jupiter:junit-jupiter:5.10.2")
}
